// Mock api para desarrollo
// simularemos el endpoint GET /accounts/:id/history

export interface Transaction {
  id: string
  accountId: string
  amount: number
  type: 'credit' | 'debit'
  status: 'pending' | 'completed' | 'failed'
  description: string
  createdAt: string
  reviewed?: boolean
 }
// Simularemos datos fijos 
const mockTransactions: Transaction[] = [
   {
    id: '1',
    accountId: 'prueba123',  
    amount: 150.00,
    type: 'credit',
    status: 'completed',
    description: 'tranferencia recibida',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    accountId: 'prueba123',  
    amount: -50.00,
    type: 'debit',
    status: 'completed',
    description: 'compra supermercado',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '3',
    accountId: 'prueba123', 
    amount: -200.00,
    type: 'debit',
    status: 'pending',
    description: 'pago  servicios',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: '4',
    accountId: 'prueba123', 
    amount: 500.00,
    type: 'credit',
    status: 'completed',
    description: 'deposito',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: '5',
    accountId: 'prueba123',  
    amount: -30.00,
    type: 'debit',
    status: 'failed',
    description: 'retiro atm',
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
  // Nuevas transacciones
  {
    id: '6',
    accountId: 'prueba123',
    amount: 85.50,
    type: 'credit',
    status: 'completed',
    description: 'tranferencia',
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: '7',
    accountId: 'prueba123',
    amount: -120.00,
    type: 'debit',
    status: 'completed',
    description: 'compras online',
    createdAt: new Date(Date.now() - 518400000).toISOString(),
  },
  {
    id: '8',
    accountId: 'prueba123',
    amount: 320.00,
    type: 'credit',
    status: 'completed',
    description: 'devolucion de impuestos rciva',
    createdAt: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: '9',
    accountId: 'prueba123',
    amount: -45.00,
    type: 'debit',
    status: 'pending',
    description: 'netfly',
    createdAt: new Date(Date.now() - 691200000).toISOString(),
  },
  {
    id: '10',
    accountId: 'prueba123',
    amount: -15.00,
    type: 'debit',
    status: 'completed',
    description: 'desayuno',
    createdAt: new Date(Date.now() - 777600000).toISOString(),
  },
  {
    id: '11',
    accountId: 'prueba123',
    amount: 210.00,
    type: 'credit',
    status: 'completed',
    description: 'pago de deuda',
    createdAt: new Date(Date.now() - 864000000).toISOString(),
  },
  {
    id: '12',
    accountId: 'prueba123',
    amount: -350.00,
    type: 'debit',
    status: 'failed',
    description: 'pago tarjeta de credito',
    createdAt: new Date(Date.now() - 950400000).toISOString(),
  },
  {
    id: '13',
    accountId: 'prueba123',
    amount: 65.00,
    type: 'credit',
    status: 'completed',
    description: 'compras',
    createdAt: new Date(Date.now() - 1036800000).toISOString(),
  },
  {
    id: '14',
    accountId: 'prueba123',
    amount: -95.00,
    type: 'debit',
    status: 'completed',
    description: 'farmacia',
    createdAt: new Date(Date.now() - 1123200000).toISOString(),
  },
  {
    id: '15',
    accountId: 'prueba123',
    amount: 180.00,
    type: 'credit',
    status: 'pending',
    description: 'tranferencia pendiente',
    createdAt: new Date(Date.now() - 1209600000).toISOString(),
  },
  {
    id: '16',
    accountId: 'prueba123',
    amount: -220.00,
    type: 'debit',
    status: 'completed',
    description: 'electrodomestico',
    createdAt: new Date(Date.now() - 1296000000).toISOString(),
  },
  {
    id: '17',
    accountId: 'prueba123',
    amount: 45.50,
    type: 'credit',
    status: 'completed',
    description: 'churrasco',
    createdAt: new Date(Date.now() - 1382400000).toISOString(),
  },
  {
    id: '18',
    accountId: 'prueba123',
    amount: -12.00,
    type: 'debit',
    status: 'completed',
    description: 'parqueo',
    createdAt: new Date(Date.now() - 1468800000).toISOString(),
  },
  {
    id: '19',
    accountId: 'prueba123',
    amount: 550.00,
    type: 'credit',
    status: 'completed',
    description: 'sueldo',
    createdAt: new Date(Date.now() - 1555200000).toISOString(),
  },
  {
    id: '20',
    accountId: 'prueba123',
    amount: -75.00,
    type: 'debit',
    status: 'pending',
    description: 'gim',
    createdAt: new Date(Date.now() - 1641600000).toISOString(),
  },
  {
    id: '21',
    accountId: 'prueba123',
    amount: 95.00,
    type: 'credit',
    status: 'completed',
    description: 'reenbolso',
    createdAt: new Date(Date.now() - 1728000000).toISOString(),
  },
  {
    id: '22',
    accountId: 'prueba123',
    amount: -280.00,
    type: 'debit',
    status: 'completed',
    description: 'ropa',
    createdAt: new Date(Date.now() - 1814400000).toISOString(),
  },
  {
    id: '23',
    accountId: 'prueba123',
    amount: 120.00,
    type: 'credit',
    status: 'completed',
    description: 'venta de garage',
    createdAt: new Date(Date.now() - 1900800000).toISOString(),
  },
  {
    id: '24',
    accountId: 'prueba123',
    amount: -65.00,
    type: 'debit',
    status: 'failed',
    description: 'servicio straming',
    createdAt: new Date(Date.now() - 1987200000).toISOString(),
  },
  {
    id: '25',
    accountId: 'prueba123',
    amount: 320.00,
    type: 'credit',
    status: 'completed',
    description: 'trabajo freelance',
    createdAt: new Date(Date.now() - 2073600000).toISOString(),
  },
   {
    id: '26',
    accountId: 'prueba123',
    amount: -42.50,
    type: 'debit',
    status: 'completed',
    description: 'cafeteria',
    createdAt: new Date(Date.now() - 2160000000).toISOString(),
  },
  {
    id: '27',
    accountId: 'prueba123',
    amount: 88.00,
    type: 'credit',
    status: 'completed',
    description: 'venta libro',
    createdAt: new Date(Date.now() - 2246400000).toISOString(),
  },
  {
    id: '28',
    accountId: 'prueba123',
    amount: -150.00,
    type: 'debit',
    status: 'pending',
    description: 'restaurante',
    createdAt: new Date(Date.now() - 2332800000).toISOString(),
  },
  {
    id: '29',
    accountId: 'prueba123',
    amount: 200.00,
    type: 'credit',
    status: 'completed',
    description: 'prestamo a colega',
    createdAt: new Date(Date.now() - 2419200000).toISOString(),
  },
  {
    id: '30',
    accountId: 'prueba123',
    amount: -35.00,
    type: 'debit',
    status: 'completed',
    description: 'desayuno',
    createdAt: new Date(Date.now() - 2505600000).toISOString(),
  },
  {
    id: '31',
    accountId: 'prueba123',
    amount: 60.00,
    type: 'credit',
    status: 'pending',
    description: 'devolucion de regalo',
    createdAt: new Date(Date.now() - 2592000000).toISOString(),
  },
  {
    id: '32',
    accountId: 'prueba123',
    amount: -99.00,
    type: 'debit',
    status: 'failed',
    description: 'cine',
    createdAt: new Date(Date.now() - 2678400000).toISOString(),
  },
  {
    id: '33',
    accountId: 'prueba123',
    amount: 125.00,
    type: 'credit',
    status: 'completed',
    description: 'pago de deuda',
    createdAt: new Date(Date.now() - 2764800000).toISOString(),
  },
  {
    id: '34',
    accountId: 'prueba123',
    amount: -55.00,
    type: 'debit',
    status: 'completed',
    description: 'farmacia',
    createdAt: new Date(Date.now() - 2851200000).toISOString(),
  },
  {
    id: '35',
    accountId: 'prueba123',
    amount: 410.00,
    type: 'credit',
    status: 'completed',
    description: 'venta de repuestos',
    createdAt: new Date(Date.now() - 2937600000).toISOString(),
  },
  {
    id: '36',
    accountId: 'prueba123',
    amount: -22.00,
    type: 'debit',
    status: 'completed',
    description: 'cena',
    createdAt: new Date(Date.now() - 3024000000).toISOString(),
  },
  {
    id: '37',
    accountId: 'prueba123',
    amount: -180.00,
    type: 'debit',
    status: 'pending',
    description: 'cambio de aceite de auto',
    createdAt: new Date(Date.now() - 3110400000).toISOString(),
  },
  {
    id: '38',
    accountId: 'prueba123',
    amount: 300.00,
    type: 'credit',
    status: 'completed',
    description: 'regalo de cumple',
    createdAt: new Date(Date.now() - 3196800000).toISOString(),
  },
  {
    id: '39',
    accountId: 'prueba123',
    amount: -75.50,
    type: 'debit',
    status: 'failed',
    description: 'pago de callduty',
    createdAt: new Date(Date.now() - 3283200000).toISOString(),
  },
  {
    id: '40',
    accountId: 'prueba123',
    amount: 95.00,
    type: 'credit',
    status: 'completed',
    description: 'seguro',
    createdAt: new Date(Date.now() - 3369600000).toISOString(),
  },
]

// Simular API con datos fijos
export const fetchTransactions = async (accountId: string, page: number = 0, pageSize: number = 20) => {
  await new Promise(resolve => setTimeout(resolve, 500))
  
  // Filtrar por accountId
  const filtered = mockTransactions.filter(tx => tx.accountId === accountId)
  const start = page * pageSize
  const data = filtered.slice(start, start + pageSize)
  const hasMore = start + pageSize < filtered.length
  
  return {
    data,
    nextPage: hasMore ? page + 1 : null,
    hasMore,
  }
}